server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.137.130:8848  #配置Nacos地址
      config:
        server-addr: 192.168.137.130:8848 #Nacos作为配置中心地址
        file-extension: yaml
    sentinel:
      transport:
        dashboard: 192.168.137.130:8858 #配置Sentinel dashboard地址
        port: 8719 #默认端口为8719，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口

management:
  endpoints:
    web:
      exposure:
        include: '*'
