#server:
#  port: 3355
#
#spring:
#  application:
#    name: cloud-config-client
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/Gu-Yang/SpringCloudLearningConfig.git
#          search-paths:
#            - SpringCloudLearningConfig
#      label: master
#
#eureka:
#  client:
#    register-with-eureka: true # 是否将自己注册进Eureka server，默认为true
#    fetch-registry: true # 是否从Eureka Server抓取已有的注册信息，默认为true，单节点无所谓，但集群必须设置为true才能配合ribbon使用负载均衡
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka #, http://eureka7002.com:7002/eureka