server:
  port: 80

spring:
  application:
    name: cloud-consumer-order80-hystrix

eureka:
  client:
    register-with-eureka: true # 是否将自己注册进Eureka server，默认为true
    fetch-registry: true # 是否从Eureka Server抓取已有的注册信息，默认为true，单节点无所谓，但集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

#CLOUD-PAYMENT-SERVICE:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.gy.springcloud.rule.MyRibbonRule

ribbon:
  ReadTimeout: 5000   #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000   #指建立连接所用的时间

feign:
  hystrix:
    enabled: true

  # 使用Hystrix Metrics Stream必备
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream