server:
  port: 3344

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gu-Yang/SpringCloudLearningConfig.git
          search-paths:
            - SpringCloudLearningConfig
      label: master
  #rabbitmq相关配置，15672是Web管理界面的端口；5672是MQ访问的端口
  rabbitmq:
    host: 192.168.137.130
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true # 是否将自己注册进Eureka server，默认为true
    fetch-registry: true # 是否从Eureka Server抓取已有的注册信息，默认为true，单节点无所谓，但集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #, http://eureka7002.com:7002/eureka

#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
