server:
  port: 9527

spring:
  application:
    name: cloud-gateway-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: order_route #路由的ID，没有固定的规则，但要求唯一，建议与服务名相对应
#        uri: http://localhost   #匹配后提供服务的路由地址，可以直接使用uri，也可以使用注册中心中的服务名
        uri: lb://CLOUD-CONSUMER-ORDER80 #匹配后提供服务的路由地址的更常用方式，可以隐藏实际地址并实现负载均衡
        predicates:
        - Path=/order/** #断言，只有断言为true的请求才会进行路由
      - id: payment_route
#        uri: http://localhost:8001
        uri: lb://CLOUD-PAYMENT-SERVICE
        predicates:
        - Path=/payment/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true # 是否将自己注册进Eureka server，默认为true
    fetch-registry: true # 是否从Eureka Server抓取已有的注册信息，默认为true，单节点无所谓，但集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    instance:
      instance-id: gateway9527  # 在eureka页面中显示的instance名称
      prefer-ip-address: true   # 在eureka页面中是否可以通过名称链接到对应的IP地址