server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.137.130:8848

service-url:
  nacos-user-service: http://nacos-payment-

# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true
